FROM elixir:1.9-alpine

ENV APP_HOME /opt/app

WORKDIR $APP_HOME

RUN apk add git 

RUN mix local.hex --force \
    && mix local.rebar --force


COPY . .

RUN mix deps.get

RUN mkdir -p $APP_HOME


CMD ["./docker/wait-for-it.sh"]
